// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs9UZdDFKiCvLcP_5HT4qumviu1b8oeZk',
    appId: '1:933418119400:web:ce162e7709d2474069d95d',
    messagingSenderId: '933418119400',
    projectId: 'qrcode-getx-5c8ea',
    authDomain: 'qrcode-getx-5c8ea.firebaseapp.com',
    storageBucket: 'qrcode-getx-5c8ea.firebasestorage.app',
    measurementId: 'G-TB469Q2DWN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjiT5n4X-CcITFALTl0khb8wBiR7ON81I',
    appId: '1:933418119400:android:e9b3435a4e4a76fb69d95d',
    messagingSenderId: '933418119400',
    projectId: 'qrcode-getx-5c8ea',
    storageBucket: 'qrcode-getx-5c8ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_l2-uQ23rbteTteBp0C-WDi3iMjzIjTA',
    appId: '1:933418119400:ios:de0930face4f4cdf69d95d',
    messagingSenderId: '933418119400',
    projectId: 'qrcode-getx-5c8ea',
    storageBucket: 'qrcode-getx-5c8ea.firebasestorage.app',
    iosBundleId: 'com.example.qrcodeGetx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_l2-uQ23rbteTteBp0C-WDi3iMjzIjTA',
    appId: '1:933418119400:ios:de0930face4f4cdf69d95d',
    messagingSenderId: '933418119400',
    projectId: 'qrcode-getx-5c8ea',
    storageBucket: 'qrcode-getx-5c8ea.firebasestorage.app',
    iosBundleId: 'com.example.qrcodeGetx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBs9UZdDFKiCvLcP_5HT4qumviu1b8oeZk',
    appId: '1:933418119400:web:3441dc8253b4e73569d95d',
    messagingSenderId: '933418119400',
    projectId: 'qrcode-getx-5c8ea',
    authDomain: 'qrcode-getx-5c8ea.firebaseapp.com',
    storageBucket: 'qrcode-getx-5c8ea.firebasestorage.app',
    measurementId: 'G-VVM0LDNL2T',
  );
}
